name: Auto Commit Streak

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: echo "Last updated on $(date)" > last-update.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "naveenselvan0004@gmail.com"
          git config --global user.name "naveencreation"
          git add .
          git commit -m "Automated commit - $(date)" || echo "No changes to commit"
          git push
